// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatToDo.Data;

namespace WhatToDo.Migrations
{
    [DbContext(typeof(WhatToDoContext))]
    [Migration("20191221195701_Correction2")]
    partial class Correction2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WhatToDo.Models.ToDo", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Duration")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("KindOfToDo")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ToDoName")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Name");

                    b.HasIndex("ToDoName");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("WhatToDo.Models.ToDo", b =>
                {
                    b.HasOne("WhatToDo.Models.ToDo", null)
                        .WithMany("List")
                        .HasForeignKey("ToDoName");
                });
#pragma warning restore 612, 618
        }
    }
}
